# Generated by Django 4.2.10 on 2024-03-01 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ProfPortal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cgpa', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, max_length=3)),
                ('branch', models.TextField(choices=[('A7', 'CS'), ('AA', 'ECE'), ('A8', 'ENI'), ('A3', 'EEE'), ('A4', 'MECH'), ('AB', 'MANU'), ('A2', 'CIVIL'), ('A1', 'CHEMICAL'), ('B5', 'Msc. PHY'), ('B1', 'Msc. BIO'), ('B2', 'Msc. CHEM'), ('A5', 'PHARMA'), ('B4', 'Msc. MATH'), ('B3', 'Msc. ECO')], max_length=2)),
                ('email', models.EmailField(max_length=254)),
                ('bits_id', models.CharField(max_length=15)),
                ('under_courses', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProfPortal.course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Enrolled_Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=15)),
                ('student_grade', models.TextField(choices=[('A', 'A'), ('A-', 'A-'), ('B', 'B'), ('B-', 'B-'), ('C', 'C'), ('C-', 'C-'), ('D', 'D'), ('E', 'E'), ('NC', 'NC')], default='Not Awarded', max_length=20)),
                ('enrolled_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentPortal.student_profile')),
            ],
        ),
        migrations.CreateModel(
            name='Course_eval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveBigIntegerField(default=0)),
                ('of_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProfPortal.course')),
                ('of_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentPortal.student_profile')),
            ],
        ),
    ]
