# Generated by Django 4.2.10 on 2024-03-02 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentPortal', '0004_remove_student_profile_under_courses_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrolled_course',
            old_name='under_courses',
            new_name='under_course',
        ),
    ]
