# Generated by Django 4.2.10 on 2024-03-02 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProfPortal', '0001_initial'),
        ('StudentPortal', '0006_enrolled_course_course_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_profile',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProfPortal.branch'),
        ),
    ]
