# Generated by Django 4.2.10 on 2024-03-02 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProfPortal', '0002_branch_branch_code'),
        ('StudentPortal', '0007_alter_student_profile_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolled_course',
            name='under_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ProfPortal.course'),
        ),
    ]
