# Generated by Django 4.2.10 on 2024-03-02 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProfPortal', '0002_branch_branch_code'),
        ('StudentPortal', '0009_enrolled_course_graded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_profile',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ProfPortal.branch'),
        ),
    ]
