# Generated by Django 4.2.10 on 2024-03-07 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentPortal', '0011_alter_course_eval_of_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolled_course',
            name='student_grade',
            field=models.TextField(default='Not Awarded', max_length=20),
        ),
    ]
