# Generated by Django 4.2.10 on 2024-03-01 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=15)),
                ('course_units', models.PositiveIntegerField(default=0)),
                ('compulsary_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ProfPortal.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ProfProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.PositiveBigIntegerField(default=0)),
                ('under_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProfPortal.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Study_Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.FileField(blank=True, null=True, upload_to='media/study_material_files/')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProfPortal.profprofile')),
                ('under_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProfPortal.course')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eval_name', models.CharField(max_length=15)),
                ('total_marks', models.PositiveIntegerField(default=0)),
                ('of_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProfPortal.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='taught_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProfPortal.profprofile'),
        ),
        migrations.AddField(
            model_name='course',
            name='under_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProfPortal.department'),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('description', models.TextField()),
                ('attached_file', models.FileField(blank=True, null=True, upload_to='media/announcement_files/')),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('by_prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProfPortal.profprofile')),
                ('under_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProfPortal.course')),
            ],
        ),
    ]
