# Generated by Django 4.2.10 on 2024-03-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfPortal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='branch_code',
            field=models.CharField(default='A7', max_length=3),
            preserve_default=False,
        ),
    ]
