# Generated by Django 4.2.10 on 2024-03-03 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProfPortal', '0002_branch_branch_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profprofile',
            name='under_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ProfPortal.department'),
        ),
    ]
