# Generated by Django 4.2.10 on 2024-03-03 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProfPortal', '0003_alter_profprofile_under_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profprofile',
            name='under_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProfPortal.department'),
        ),
    ]
