# Generated by Django 4.2.10 on 2024-03-04 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProfPortal', '0004_alter_profprofile_under_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'permissions': [('is_prof', 'is a prof')]},
        ),
    ]
