# Generated by Django 4.2.10 on 2024-03-04 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProfPortal', '0005_alter_course_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'permissions': [('is_prof', 'is a prof'), ('is_student', 'is a student')]},
        ),
    ]
