# Generated by Django 4.2.10 on 2024-03-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfPortal', '0006_alter_course_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='compulsary_to',
        ),
        migrations.AddField(
            model_name='course',
            name='compulsary_to',
            field=models.ManyToManyField(blank=True, null=True, to='ProfPortal.branch'),
        ),
    ]
