# Generated by Django 4.2.10 on 2024-03-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfPortal', '0007_remove_course_compulsary_to_course_compulsary_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='compulsary_to',
            field=models.ManyToManyField(blank=True, to='ProfPortal.branch'),
        ),
    ]
