# Generated by Django 4.2.10 on 2024-03-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfPortal', '0008_alter_course_compulsary_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(default='a', max_length=9),
            preserve_default=False,
        ),
    ]
